//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabio_managment_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int Id_client { get; set; }
        public string Nome { get; set; }
        public string Apelido { get; set; }
        public int Idade { get; set; }
        public string Pagamento { get; set; }
        public string Corte { get; set; }
    }
}
